#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Split overlap-based peak sets by primary_region_class.

Inputs
------
- processed/peaks/comparison_sets/overlaps/overlap_summary.tsv
- processed/peaks/comparison_sets/overlaps/overlap_file_manifest.tsv

Per-comparison required files
-----------------------------
From overlap_file_manifest.tsv:
- shared_left_bed
- shared_right_bed
- left_specific_bed
- right_specific_bed
- shared_left_annotations_tsv
- shared_right_annotations_tsv
- left_specific_annotations_tsv
- right_specific_annotations_tsv

Outputs
-------
- processed/peaks/comparison_sets/by_region/region_specific_peak_summary.tsv
- processed/peaks/comparison_sets/by_region/region_specific_file_manifest.tsv
- processed/peaks/comparison_sets/by_region/<comparison_id>/<set_name>.<region>.annotation_ready.bed
- processed/peaks/comparison_sets/by_region/<comparison_id>/<set_name>.<region>.annotations.tsv
- logs/split_peak_sets_by_region_class.log

Notes
-----
- Splitting is based on the existing primary_region_class field in annotation TSVs.
- BED subsets are generated by matching peak_id between BED6 and annotation TSV.
- Default regions cover all currently used classes; you can restrict with --regions.
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Set


DEFAULT_REGIONS = [
    "five_prime_utr",
    "three_prime_utr",
    "utr",
    "CDS",
    "exon",
    "intron",
    "gene",
    "intergenic",
]

SET_SPECS = [
    ("shared_left", "shared_left_bed", "shared_left_annotations_tsv"),
    ("shared_right", "shared_right_bed", "shared_right_annotations_tsv"),
    ("left_specific", "left_specific_bed", "left_specific_annotations_tsv"),
    ("right_specific", "right_specific_bed", "right_specific_annotations_tsv"),
]

ANNOTATION_COLUMNS = [
    "peak_id",
    "chrom",
    "start",
    "end",
    "score",
    "strand",
    "target_label",
    "biosample_term_name",
    "experiment_accession",
    "selected_file_accession",
    "primary_region_class",
    "overlap_gene_ids",
    "overlap_gene_names",
    "overlap_transcript_ids",
    "n_primary_region_features",
]

SUMMARY_COLUMNS = [
    "comparison_id",
    "priority_rank",
    "priority_level",
    "comparison_scope",
    "comparison_type",
    "left_target_label",
    "left_biosample_term_name",
    "left_experiment_accession",
    "left_selected_file_accession",
    "right_target_label",
    "right_biosample_term_name",
    "right_experiment_accession",
    "right_selected_file_accession",
    "set_name",
    "region_class",
    "input_set_peak_count",
    "region_peak_count",
    "region_fraction_within_set",
    "status",
    "note",
]

FILE_MANIFEST_COLUMNS = [
    "comparison_id",
    "set_name",
    "region_class",
    "output_bed_path",
    "output_annotation_tsv_path",
    "region_peak_count",
    "status",
    "note",
]


def now_str() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def log(msg: str, log_path: Optional[Path] = None) -> None:
    print(msg, flush=True)
    if log_path is not None:
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with log_path.open("a", encoding="utf-8") as f:
            f.write(f"[{now_str()}] {msg}\n")


def ensure_project_root() -> Path:
    script_path = Path(__file__).resolve()
    return script_path.parents[2]


def normalize_text(x: Any) -> str:
    if x is None:
        return ""
    return str(x).strip()


def safe_int(x: Any, default: Optional[int] = None) -> Optional[int]:
    try:
        return int(str(x).strip())
    except Exception:
        return default


def safe_filename_part(text: str) -> str:
    s = normalize_text(text)
    if not s:
        return "NA"
    out = []
    for ch in s:
        if ch.isalnum() or ch in {"-", "_", "."}:
            out.append(ch)
        else:
            out.append("_")
    x = "".join(out)
    while "__" in x:
        x = x.replace("__", "_")
    return x.strip("_") or "NA"


def read_tsv_rows(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        return list(reader)


def write_tsv(path: Path, rows: List[Dict[str, Any]], fieldnames: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t", extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in fieldnames})


def build_index(rows: List[Dict[str, str]], key: str) -> Dict[str, Dict[str, str]]:
    idx: Dict[str, Dict[str, str]] = {}
    for row in rows:
        k = normalize_text(row.get(key))
        if k:
            idx[k] = row
    return idx


def read_bed6_rows(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for i, raw in enumerate(f, start=1):
            line = raw.rstrip("\n")
            if not line.strip():
                continue
            fields = line.split("\t")
            if len(fields) < 6:
                fields = line.split()
            if len(fields) < 6:
                continue

            chrom = fields[0]
            start = safe_int(fields[1], None)
            end = safe_int(fields[2], None)
            peak_id = fields[3]
            score = fields[4]
            strand = fields[5]

            if start is None or end is None or end <= start:
                continue

            rows.append({
                "row_index": i,
                "chrom": chrom,
                "start": start,
                "end": end,
                "peak_id": peak_id,
                "score": score,
                "strand": strand,
                "fields": fields,
                "line": line,
            })
    return rows


def subset_bed_rows(rows: List[Dict[str, Any]], keep_ids: Set[str]) -> List[Dict[str, Any]]:
    return [r for r in rows if r["peak_id"] in keep_ids]


def write_bed(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(row["line"] + "\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Split overlap-based peak sets by primary_region_class."
    )
    parser.add_argument(
        "--overlap-summary",
        default=None,
        help="Override processed/peaks/comparison_sets/overlaps/overlap_summary.tsv",
    )
    parser.add_argument(
        "--overlap-file-manifest",
        default=None,
        help="Override processed/peaks/comparison_sets/overlaps/overlap_file_manifest.tsv",
    )
    parser.add_argument(
        "--regions",
        nargs="*",
        default=None,
        help="Regions to keep, e.g. intron CDS",
    )
    parser.add_argument(
        "--priority-levels",
        nargs="*",
        default=None,
        help="Restrict to these priority levels",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Only process first N eligible comparisons",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = ensure_project_root()

    overlap_dir = root / "processed" / "peaks" / "comparison_sets" / "overlaps"
    overlap_summary_path = (
        Path(args.overlap_summary).resolve()
        if args.overlap_summary
        else overlap_dir / "overlap_summary.tsv"
    )
    overlap_file_manifest_path = (
        Path(args.overlap_file_manifest).resolve()
        if args.overlap_file_manifest
        else overlap_dir / "overlap_file_manifest.tsv"
    )

    out_dir = root / "processed" / "peaks" / "comparison_sets" / "by_region"
    summary_out = out_dir / "region_specific_peak_summary.tsv"
    file_manifest_out = out_dir / "region_specific_file_manifest.tsv"
    log_path = root / "logs" / "split_peak_sets_by_region_class.log"

    regions = args.regions if args.regions else DEFAULT_REGIONS
    regions = [normalize_text(r) for r in regions if normalize_text(r)]

    log(f"[INFO] Project root: {root}", log_path)
    log(f"[INFO] Overlap summary TSV: {overlap_summary_path}", log_path)
    log(f"[INFO] Overlap file manifest TSV: {overlap_file_manifest_path}", log_path)
    log(f"[INFO] Regions to split: {', '.join(regions)}", log_path)

    overlap_summary_rows = read_tsv_rows(overlap_summary_path)
    overlap_file_manifest_rows = read_tsv_rows(overlap_file_manifest_path)
    overlap_file_manifest_idx = build_index(overlap_file_manifest_rows, "comparison_id")

    if args.priority_levels:
        allowed = {normalize_text(x) for x in args.priority_levels if normalize_text(x)}
        overlap_summary_rows = [
            r for r in overlap_summary_rows
            if normalize_text(r.get("priority_level")) in allowed
        ]

    overlap_summary_rows = [
        r for r in overlap_summary_rows
        if normalize_text(r.get("status")) == "ok"
    ]

    overlap_summary_rows = sorted(
        overlap_summary_rows,
        key=lambda r: (
            normalize_text(r.get("priority_level")),
            normalize_text(r.get("priority_rank")),
            normalize_text(r.get("comparison_id")),
        ),
    )

    if args.limit is not None:
        overlap_summary_rows = overlap_summary_rows[:args.limit]

    log(f"[INFO] Eligible comparisons: {len(overlap_summary_rows)}", log_path)

    summary_rows: List[Dict[str, Any]] = []
    file_manifest_rows: List[Dict[str, Any]] = []

    for i, meta in enumerate(overlap_summary_rows, start=1):
        comparison_id = normalize_text(meta.get("comparison_id"))
        manifest_row = overlap_file_manifest_idx.get(comparison_id)

        log(f"[INFO] [{i}/{len(overlap_summary_rows)}] Splitting by region for {comparison_id}", log_path)

        if manifest_row is None:
            for set_name, _, _ in SET_SPECS:
                for region in regions:
                    summary_rows.append({
                        "comparison_id": comparison_id,
                        "priority_rank": normalize_text(meta.get("priority_rank")),
                        "priority_level": normalize_text(meta.get("priority_level")),
                        "comparison_scope": normalize_text(meta.get("comparison_scope")),
                        "comparison_type": normalize_text(meta.get("comparison_type")),
                        "left_target_label": normalize_text(meta.get("left_target_label")),
                        "left_biosample_term_name": normalize_text(meta.get("left_biosample_term_name")),
                        "left_experiment_accession": normalize_text(meta.get("left_experiment_accession")),
                        "left_selected_file_accession": normalize_text(meta.get("left_selected_file_accession")),
                        "right_target_label": normalize_text(meta.get("right_target_label")),
                        "right_biosample_term_name": normalize_text(meta.get("right_biosample_term_name")),
                        "right_experiment_accession": normalize_text(meta.get("right_experiment_accession")),
                        "right_selected_file_accession": normalize_text(meta.get("right_selected_file_accession")),
                        "set_name": set_name,
                        "region_class": region,
                        "input_set_peak_count": 0,
                        "region_peak_count": 0,
                        "region_fraction_within_set": 0.0,
                        "status": "missing_overlap_file_manifest",
                        "note": "comparison_id_not_found_in_overlap_file_manifest",
                    })
            continue

        comparison_subdir = out_dir / safe_filename_part(comparison_id)

        for set_name, bed_key, ann_key in SET_SPECS:
            input_bed = root / normalize_text(manifest_row.get(bed_key))
            input_ann = root / normalize_text(manifest_row.get(ann_key))

            if not input_bed.exists() or not input_ann.exists():
                for region in regions:
                    summary_rows.append({
                        "comparison_id": comparison_id,
                        "priority_rank": normalize_text(meta.get("priority_rank")),
                        "priority_level": normalize_text(meta.get("priority_level")),
                        "comparison_scope": normalize_text(meta.get("comparison_scope")),
                        "comparison_type": normalize_text(meta.get("comparison_type")),
                        "left_target_label": normalize_text(meta.get("left_target_label")),
                        "left_biosample_term_name": normalize_text(meta.get("left_biosample_term_name")),
                        "left_experiment_accession": normalize_text(meta.get("left_experiment_accession")),
                        "left_selected_file_accession": normalize_text(meta.get("left_selected_file_accession")),
                        "right_target_label": normalize_text(meta.get("right_target_label")),
                        "right_biosample_term_name": normalize_text(meta.get("right_biosample_term_name")),
                        "right_experiment_accession": normalize_text(meta.get("right_experiment_accession")),
                        "right_selected_file_accession": normalize_text(meta.get("right_selected_file_accession")),
                        "set_name": set_name,
                        "region_class": region,
                        "input_set_peak_count": 0,
                        "region_peak_count": 0,
                        "region_fraction_within_set": 0.0,
                        "status": "missing_input",
                        "note": "input_bed_or_annotation_tsv_missing",
                    })
                continue

            bed_rows = read_bed6_rows(input_bed)
            ann_rows = read_tsv_rows(input_ann)
            ann_idx = build_index(ann_rows, "peak_id")

            input_set_peak_count = len(bed_rows)

            region_to_ids: Dict[str, Set[str]] = {region: set() for region in regions}
            for ann in ann_rows:
                pid = normalize_text(ann.get("peak_id"))
                region = normalize_text(ann.get("primary_region_class"))
                if pid and region in region_to_ids:
                    region_to_ids[region].add(pid)

            for region in regions:
                keep_ids = region_to_ids[region]
                subset_bed = subset_bed_rows(bed_rows, keep_ids)
                subset_ann = [ann_idx[pid] for pid in sorted(keep_ids) if pid in ann_idx]

                out_bed = comparison_subdir / f"{set_name}.{region}.annotation_ready.bed"
                out_ann = comparison_subdir / f"{set_name}.{region}.annotations.tsv"

                write_bed(out_bed, subset_bed)
                write_tsv(out_ann, subset_ann, ANNOTATION_COLUMNS)

                region_peak_count = len(subset_bed)
                region_fraction = (region_peak_count / input_set_peak_count) if input_set_peak_count > 0 else 0.0

                summary_rows.append({
                    "comparison_id": comparison_id,
                    "priority_rank": normalize_text(meta.get("priority_rank")),
                    "priority_level": normalize_text(meta.get("priority_level")),
                    "comparison_scope": normalize_text(meta.get("comparison_scope")),
                    "comparison_type": normalize_text(meta.get("comparison_type")),
                    "left_target_label": normalize_text(meta.get("left_target_label")),
                    "left_biosample_term_name": normalize_text(meta.get("left_biosample_term_name")),
                    "left_experiment_accession": normalize_text(meta.get("left_experiment_accession")),
                    "left_selected_file_accession": normalize_text(meta.get("left_selected_file_accession")),
                    "right_target_label": normalize_text(meta.get("right_target_label")),
                    "right_biosample_term_name": normalize_text(meta.get("right_biosample_term_name")),
                    "right_experiment_accession": normalize_text(meta.get("right_experiment_accession")),
                    "right_selected_file_accession": normalize_text(meta.get("right_selected_file_accession")),
                    "set_name": set_name,
                    "region_class": region,
                    "input_set_peak_count": input_set_peak_count,
                    "region_peak_count": region_peak_count,
                    "region_fraction_within_set": round(region_fraction, 6),
                    "status": "ok",
                    "note": "region_split_completed",
                })

                file_manifest_rows.append({
                    "comparison_id": comparison_id,
                    "set_name": set_name,
                    "region_class": region,
                    "output_bed_path": str(out_bed.relative_to(root)),
                    "output_annotation_tsv_path": str(out_ann.relative_to(root)),
                    "region_peak_count": region_peak_count,
                    "status": "ok",
                    "note": "region_split_completed",
                })

    summary_rows = sorted(
        summary_rows,
        key=lambda r: (
            normalize_text(r.get("priority_level")),
            normalize_text(r.get("priority_rank")),
            normalize_text(r.get("comparison_id")),
            normalize_text(r.get("set_name")),
            normalize_text(r.get("region_class")),
        ),
    )

    file_manifest_rows = sorted(
        file_manifest_rows,
        key=lambda r: (
            normalize_text(r.get("comparison_id")),
            normalize_text(r.get("set_name")),
            normalize_text(r.get("region_class")),
        ),
    )

    write_tsv(summary_out, summary_rows, SUMMARY_COLUMNS)
    write_tsv(file_manifest_out, file_manifest_rows, FILE_MANIFEST_COLUMNS)

    n_ok = sum(1 for r in summary_rows if normalize_text(r.get("status")) == "ok")
    n_bad = len(summary_rows) - n_ok

    log("", log_path)
    log("[DONE] Region-based peak set splitting completed.", log_path)
    log(f"[DONE] Summary TSV: {summary_out}", log_path)
    log(f"[DONE] File manifest TSV: {file_manifest_out}", log_path)
    log(f"[INFO] OK rows      : {n_ok}", log_path)
    log(f"[INFO] Problem rows : {n_bad}", log_path)

    # show the strongest region-specific subsets
    best_rows = sorted(
        [r for r in summary_rows if normalize_text(r.get("status")) == "ok"],
        key=lambda r: (
            -safe_int(r.get("region_peak_count"), 0),
            normalize_text(r.get("comparison_id")),
        ),
    )[:12]

    log("[INFO] Top region-split subsets:", log_path)
    for r in best_rows:
        log(
            "  " + " | ".join([
                normalize_text(r.get("comparison_id")),
                normalize_text(r.get("set_name")),
                normalize_text(r.get("region_class")),
                f"n={normalize_text(r.get('region_peak_count'))}",
                f"frac={normalize_text(r.get('region_fraction_within_set'))}",
            ]),
            log_path,
        )

    return 0 if n_bad == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())